Identity service
KiSSel3/RentMyCar pull request #2
Opened 2024-10-07 17:44 UTC by KiSSel3

- Authorization logic
- Administrator functionality

2024-10-08 12:13 UTC, TarasovaVeronika requested changes

2024-10-08 12:13 UTC, TarasovaVeronika commented on src/Services/IdentityService/IdentityService.BLL/Services/Implementation/AuthService.cs
> +    public AuthService(UserManager<UserEntity> userManager, ITokenProvider tokenProvider, IMapper mapper, ILogger<AuthService> logger)
Write the parameters in a column

2024-10-08 12:13 UTC, TarasovaVeronika commented on src/Services/IdentityService/IdentityService.BLL/Services/Implementation/RoleService.cs
> +        var role = await _roleManager.FindByNameAsync(roleName) ??
use if() for any checking
apply to other files

2024-10-08 12:13 UTC, TarasovaVeronika commented on src/Services/IdentityService/IdentityService.DAL/Stores/RoleEntityStore.cs
> +        if (Guid.TryParse(userId, out var id))
Can we transfer this checking to service?

2024-10-08 14:53 UTC, KiSSel3 commented
The standard implementation of FindByIdAsync uses the base method ConvertIdFromString(userId):
```
    public override Task<TUser?> FindByIdAsync(string userId, CancellationToken cancellationToken = default(CancellationToken))
    {
        cancellationToken.ThrowIfCancellationRequested();
        ThrowIfDisposed();
        var id = ConvertIdFromString(userId);
        return UsersSet.FindAsync(new object?[] { id }, cancellationToken).AsTask();
    }
```

No additional checks are required.

2024-10-17 12:29 UTC, TarasovaVeronika requested changes

2024-10-17 12:29 UTC, TarasovaVeronika commented on src/Services/IdentityService/IdentityService.Presentation/Controllers/RoleController.cs
> +    public async Task<ActionResult> GetRoleById(string roleId, CancellationToken cancellationToken = default)
Can we get a GUID from route for Id? 
I think it can help us avoid parsing feature in the future.

2024-10-17 18:08 UTC, KiSSel3 commented on src/Services/IdentityService/IdentityService.Presentation/Controllers/RoleController.cs
> +    public async Task<ActionResult> GetRoleById(string roleId, CancellationToken cancellationToken = default)
No, we can't retrieve a GUID directly from the route in this case because I am overriding a method with the signature
 `public virtual Task<TRole?> FindByIdAsync(string id, CancellationToken cancellationToken = default(CancellationToken))`
 Since the method expects the ID to be passed as a string (a characteristic of UserManager), I have to pass the ID in string format.

2024-10-18 08:33 UTC, TarasovaVeronika approved these changes

2024-10-18 08:36 UTC, merged