CarManagement Service
KiSSel3/RentMyCar pull request #3
Opened 2024-10-18 07:33 UTC by KiSSel3

2024-10-24 08:38 UTC, TarasovaVeronika requested changes

2024-10-24 08:38 UTC, TarasovaVeronika commented on src/Services/CarManagementService/CarManagementService.Presentation/Controllers/CarController.cs
> +        Response.Headers.Append("X-Pagination", JsonConvert.SerializeObject(metadata));
What do you think about custom page list (smth like as new response model)?  Is it better than your realization?

2024-10-24 08:38 UTC, TarasovaVeronika commented on src/Services/CarManagementService/CarManagementService.Presentation/Controllers/CarController.cs
> +    public async Task<IActionResult> GetCarsByParametersAsync([FromForm] CarParametersRequestDTO request, CancellationToken cancellationToken = default)
Can we use [FromBody] for request? I think that FromForm better when we want to work with sending files for example

2024-10-24 08:38 UTC, TarasovaVeronika commented on src/Services/CarManagementService/CarManagementService.Application/UseCases/Commands/Brand/CreateBrand/CreateBrandCommand.cs
> +namespace CarManagementService.Application.UseCases.Commands.Brand.CreateBrand;
What do you think about change you application disign? 
Like as: UseCase -> Command, Query, CommandHandler, QueryHandlers -> Command/Qery/Handlers looks like (Brand, Car and ect folders)

2024-10-24 08:38 UTC, TarasovaVeronika commented on src/Services/CarManagementService/CarManagementService.Application/UseCases/Commands/Brand/CreateBrand/CreateBrandCommandValidator.cs
> +        RuleFor(command => command.Name)
May be can be better to validate request model in API layer?

2024-10-24 08:38 UTC, TarasovaVeronika commented on src/Services/CarManagementService/CarManagementService.Application/UseCases/Queries/CarModel/GetCarModelByBrandIdAndName/GetCarModelByBrandIdAndNameQueryHandler.cs
> +            throw new EntityNotFoundException($"Car model with Brand ID {request.BrandId} and Name {request.Name} was not found.");
What do you think about adding errors' loggin?

2024-10-25 13:06 UTC, KiSSel3 commented on src/Services/CarManagementService/CarManagementService.Application/UseCases/Queries/CarModel/GetCarModelByBrandIdAndName/GetCarModelByBrandIdAndNameQueryHandler.cs
> +            throw new EntityNotFoundException($"Car model with Brand ID {request.BrandId} and Name {request.Name} was not found.");
Errors are logged at the global exception handler level

2024-10-29 08:28 UTC, TarasovaVeronika approved these changes

2024-10-29 10:03 UTC, merged